### ISSUE TITLE
websphere-liberty-controller pod keeps restarting when deploying WebSphereLibertyApplication as statefulSet with semeruCloudCompiler enabled in AKS

### ISSUE THREAD

**Issue by tam512** [WASdev/websphere-liberty-operator#358]
This problem is seen in Azure Kubernetes Service cluster.  
Deploy daytrader7 application with WebSphere Liberty Operator 1.1.0 and semeruCloudCompiler enabled
The following is part of the application deploy yaml
```
apiVersion: liberty.websphere.ibm.com/v1
kind: WebSphereLibertyApplication
metadata:
  name: daytrader7
spec:
  license:
    accept: true
    edition: IBM WebSphere Application Server
    productEntitlementSource: Standalone
    metric: Virtual Processor Core (VPC)
  semeruCloudCompiler:
    enable: true
    replicas: 1
  statefulSet:
    updateStrategy:
      type: RollingUpdate
..........
```
After deploying the application, I see the following errors when describe the WebSphereLibertyApplication
```
% kubectl get wlapps
NAME         IMAGE                                                                                                               EXPOSED   RECONCILED   RESOURCESREADY   READY   AGE
daytrader7   hyc-wassvt-team-image-registry-docker-local.artifactory.swg-devops.com/daytrader/sample-daytrader7:ol-jdk8-java17   true      True         False            True    45m

% kubectl describe wlapp daytrader7
.................
........................
Events:
  Type     Reason           Age                From                        Message
  ----     ------           ----               ----                        -------
  Warning  ProcessingError  46m                websphere-liberty-operator  Operation cannot be fulfilled on webspherelibertyapplications.liberty.websphere.ibm.com "daytrader7": the object has been modified; please apply your changes to the latest version and try again
  Warning  ProcessingError  46m (x2 over 46m)  websphere-liberty-operator  Certificate is not ready
  Warning  ProcessingError  46m                websphere-liberty-operator  Operation cannot be fulfilled on deployments.apps "daytrader7-semeru-compiler-1": the object has been modified; please apply your changes to the latest version and try again
  Warning  ProcessingError  45m (x9 over 46m)  websphere-liberty-operator  Semeru Cloud Compiler is not ready: Deployment is not ready.
  Warning  ProcessingError  45m                websphere-liberty-operator  Secret "daytrader7-svc-tls-cm" was not found in namespace "daytrader-java17", Secret "daytrader7-svc-tls-cm" not found
  Warning  ProcessingError  25m                websphere-liberty-operator  Operation cannot be fulfilled on webspherelibertyapplications.liberty.websphere.ibm.com "daytrader7": the object has been modified; please apply your changes to the latest version and try again
  Warning  ProcessingError  15m (x3 over 15m)  websphere-liberty-operator  Semeru Cloud Compiler is not ready: Deployment is not ready.
```
-  Checking on the _websphere-liberty-controller-manager_ pod, I see it keeps restarting and these are errors in the log
```
panic: runtime error: index out of range [0] with length 0

goroutine 539 [running]:
github.com/WASdev/websphere-liberty-operator/utils.AddSecretResourceVersionAsEnvVar(0xc000d025a8, 0xc0002f8e00, {0x1a4b020, 0xc00069af00}, {0xc00081f080, 0x23}, {0x17e6401, 0xa})
	/workspace/utils/utils.go:180 +0x30b
github.com/WASdev/websphere-liberty-operator/controllers.(*ReconcileWebSphereLiberty).Reconcile.func8()
	/workspace/controllers/webspherelibertyapplication_controller.go:483 +0x854
sigs.k8s.io/controller-runtime/pkg/controller/controllerutil.mutate(0xc000528a00?, {{0xc0008b3b40?, 0xc000138318?}, {0xc0008b3b30?, 0xc00089b0b8?}}, {0x1a57040, 0xc000528a00})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/controller/controllerutil/controllerutil.go:339 +0x4f
sigs.k8s.io/controller-runtime/pkg/controller/controllerutil.CreateOrUpdate({0x1a44248, 0xc000138318}, {0x1a4b020, 0xc00069af00}, {0x1a57040?, 0xc000528a00}, 0x8?)
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/controller/controllerutil/controllerutil.go:211 +0x250
github.com/application-stacks/runtime-component-operator/utils.(*ReconcilerBase).CreateOrUpdate(0xc00081acf0, {0x1a57040?, 0xc000528a00}, {0x1a55750?, 0xc0002f8e00?}, 0x17fa6c0?)
	/go/pkg/mod/github.com/application-stacks/runtime-component-operator@v1.0.0-20220602-0850.0.20221117174943-84c52c5b5811/utils/reconciler.go:116 +0xf8
github.com/WASdev/websphere-liberty-operator/controllers.(*ReconcileWebSphereLiberty).Reconcile(0xc00081acf0, {0xc00025f2c0?, 0x15f5700?}, {{{0xc000777240?, 0x1714fc0?}, {0xc000777236?, 0x30?}}})
	/workspace/controllers/webspherelibertyapplication_controller.go:453 +0x24f8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc00055a000, {0x1a442b8, 0xc00025f2c0}, {{{0xc000777240?, 0x1714fc0?}, {0xc000777236?, 0x4045d4?}}})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:114 +0x28b
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00055a000, {0x1a44210, 0xc0003f87c0}, {0x16525e0?, 0xc00069d6c0?})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:311 +0x352
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00055a000, {0x1a44210, 0xc0003f87c0})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:223 +0x31c

```

**Comment by tam512** [comment]
@leochr mentioned that this problem is specific to statefulSet.  I just tried to deploy the app again as deployment and I don't see this issue.

**Comment by leochr** [comment]
@tam512  Validated that this Stateful related issue is resolved with new pre-release driver (Dec 6th). You can try Semeru compiler with StatefulSet now.
